### ISSUE TITLE
Cannot set HTTP Status Code to signal success/failure of request handling

### ISSUE THREAD

**Issue by thfi** [N-Ziermann/restAPY#2]
The current code does not allow to set the HTTP status code for requests being handled. When implementing a function to handle a specific request, this function may provide a data structure that will be serialized into JSON, but the implementation cannot tell restAPY whether the function succeeded or failed in handling the request; restAPY will always return HTTP status 200 to the client.

**Comment by N-Ziermann** [comment]
Good point. I'll fix that
